SELECT * FROM dbo.customer

--Total revenue generated by male vs female customers
SELECT gender, SUM(purchase_amount) AS revenue 
FROM dbo.customer
GROUP BY gender

--Which customers used a discount but still spent more than the average purchase amount
SELECT customer_id 
FROM dbo.customer
WHERE discount_applied = 'Yes' AND purchase_amount>(SELECT AVG(purchase_amount) FROM dbo.customer)

--Which are the top 5 products with the highest average rating
SELECT TOP 5 item_purchased, ROUND(AVG(review_rating),2) AS average_review_rating
FROM dbo.customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC

--Compare the average purchase amounts between standard and express shipping
SELECT shipping_type, ROUND(AVG(purchase_amount),2) AS average_purchase_amount
FROM dbo.customer
WHERE shipping_type='Express' OR shipping_type='Standard'
GROUP BY shipping_type
ORDER BY average_purchase_amount DESC

--Do subscribed customers spend more? Comparing average spend and total revenue between subscribers and non-subscribers
SELECT COUNT(customer_id) AS customer_number, ROUND(AVG(purchase_amount),2) AS average_purchase_amount,ROUND(SUM(purchase_amount),2) AS revenue, subscription_status
FROM dbo.customer
GROUP BY subscription_status
ORDER BY average_purchase_amount,revenue DESC

--Which 5 products have the highest percentage of purchases with discounts applied?
SELECT TOP 5 item_purchased,
SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) AS total_with_discount,
COUNT(*) AS total_transactions,
ROUND((SUM(CASE WHEN discount_applied = 'Yes' THEN 1.0 ELSE 0.0 END) / COUNT(*)) * 100,2) AS discount_percentage
FROM customer
GROUP by item_purchased
ORDER BY discount_percentage DESC;

--Segment customers into New, Returning, and Loyal based on their total number of previous purchases and show the count of each segment
SELECT customer_id, (
	CASE 
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	WHEN previous_purchases >10 THEN 'Loyal'
	END) AS customer_type
FROM customer
GROUP BY customer_id