SELECT * FROM dbo.customer

--Total revenue generated by male vs female customers
SELECT gender, SUM(purchase_amount) AS revenue 
FROM dbo.customer
GROUP BY gender

--Which customers used a discount but still spent more than the average purchase amount
SELECT customer_id 
FROM dbo.customer
WHERE discount_applied = 'Yes' AND purchase_amount>(SELECT AVG(purchase_amount) FROM dbo.customer)

--Which are the top 5 products with the highest average rating
SELECT TOP 5 item_purchased, ROUND(AVG(review_rating),2) AS average_review_rating
FROM dbo.customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC

--Compare the average purchase amounts between standard and express shipping
SELECT shipping_type, ROUND(AVG(purchase_amount),2) AS average_purchase_amount
FROM dbo.customer
WHERE shipping_type='Express' OR shipping_type='Standard'
GROUP BY shipping_type
ORDER BY average_purchase_amount DESC

--Do subscribed customers spend more? Comparing average spend and total revenue between subscribers and non-subscribers
SELECT COUNT(customer_id) AS customer_number, ROUND(AVG(purchase_amount),2) AS average_purchase_amount,ROUND(SUM(purchase_amount),2) AS revenue, subscription_status
FROM dbo.customer
GROUP BY subscription_status
ORDER BY average_purchase_amount,revenue DESC

--Which 5 products have the highest percentage of purchases with discounts applied?
SELECT TOP 5 item_purchased,
SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) AS total_with_discount,
COUNT(*) AS total_transactions,
ROUND((SUM(CASE WHEN discount_applied = 'Yes' THEN 1.0 ELSE 0.0 END) / COUNT(*)) * 100,2) AS discount_percentage
FROM customer
GROUP by item_purchased
ORDER BY discount_percentage DESC;

--Segment customers into New, Returning, and Loyal based on their total number of previous purchases and show the count of each segment
WITH customer_type AS (
SELECT customer_id, previous_purchases,
CASE
	WHEN previous_purchases =1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
FROM dbo.customer)

SELECT customer_segment, COUNT(*) AS 'Number of customers'
FROM customer_type
GROUP BY customer_segment;

--What are the top 3 most purchased products in each category
WITH item_counts AS (
SELECT category, item_purchased,
COUNT(customer_id) AS total_orders,
ROW_NUMBER() OVER (
PARTITION BY category ORDER BY COUNT(customer_id) DESC)
AS item_rank
FROM customer
group by category, item_purchased
)

SELECT item_rank, category, item_purchased, total_orders
FROM item_counts 
WHERE item_rank<=3

--Are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?
SELECT 
    SUM(CASE WHEN previous_purchases > 5 THEN 1 ELSE 0 END) AS repeat_buyers_count,
    SUM(CASE WHEN previous_purchases <= 5 THEN 1 ELSE 0 END) AS non_repeat_buyers_count,
	ROUND(
		(SUM(CASE WHEN previous_purchases > 5 THEN 100.0 ELSE 0.0 END) / COUNT(*)),2) AS percent_per_repeat
FROM customer
WHERE subscription_status = 'Yes';

--What is the revenue contribution for each age group
SELECT DISTINCT age_group 
FROM customer

SELECT DISTINCT age_group, SUM(purchase_amount) AS revenue_per_age_group
FROM customer
GROUP BY age_group 
ORDER BY revenue_per_age_group DESC


